export const TYPE = 'TYPE';

export const Types = {
    TYPE:'TYPE',
    LOGIN_USER:'LOGIN_USER',
    GET_USER:'GET_USER',
    SET_USER_LOGGED_IN:'SET_USER_LOGGED_IN',
    SET_USER:'SET_USER',
    SET_USER_ERROR:'SET_USER_ERROR',
    LOG_OUT:'LOG_OUT',
    GET_CATEGORY:'GET_CATEGORY',
    ERROR_CATEGORY:'ERROR_CATEGORY',
    LOADING_ON:'LOADING_ON',
    LOADING_OFF:'LOADING_OFF',
    GET_PRODUCT:'GET_PRODUCT',
    SET_PRODUCT:'SET_PRODUCT',
    ERROR_PRODUCT:'ERROR_PRODUCT'
}

